### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by ghost** [pjreddie/darknet#1]
@pjreddie How is this project different from caffe 
and how do i use it in CPU only ..is it complete project

**Comment by sunilrao43** [comment]
@pjreddie  could you also let me know an example say alex net on imagenet database on CPU

**Comment by sunilrao43** [comment]
@pjreddie waiting for reply 
thanks in advance

**Comment by pjreddie** [comment]
HEY GHOST! Here's an example of Alexnet!

https://pjreddie.com/darknet/imagenet/#alexnet

We are different from caffe because our name is different, DARKNET, it's a scarier name that implies evildoings, misdeeds, general mischief. Also we are faster and better and I heard caffe only supports Windows, I've never tried it, that's just what I heard. Plus you can train on GPUs. Can't do that in caffe can you???? Plus they are named after coffee and coffee is gross.

🔥 ☕️ 🔥

**Comment by andeyeluguo** [comment]
haha ,the name of darknet is so cool .
and I think the author is a doubi(just kiding),
also ,the naive caffe support linux ,but it needs too much lib.
I will try the reproduce the xnornet in darknet
