### ISSUE TITLE
should I resize all images to the same size for training classifier?

### ISSUE THREAD

**Issue by yanchao12122** [pjreddie/darknet#153]
I want to train my own classifier, but my images has any sizes( i.e. 100x100, 443x500, ...)
should I resize them to 448x488 or 224x224?

**Comment by TheMikeyR** [comment]
@yanchao12122 did you have an answer for this, because I'm in doubt as well, I know yolo resizes the input image, but does it pad the image to preserve the original aspect ratio? I had good success without resizing my original images (1920x1080), but still curious if I can gain any performance with some preprocessing.
