### ISSUE TITLE
Size of anchor boxes / Grid Cells

### ISSUE THREAD

**Issue by Arktius** [pjreddie/darknet#1653]
Hej guys!

I have several questions:

- Let's assume that the objects almost always have the same size. Could I use the pixel values for the anchor boxes?
- Why do I have to multiply the results of gen_anchors.py by 32? Where does this number come from?
- Where does the number 13 came up for the grid cells? Does it depend on the input size of the network?
- Is it true that one can only find a single object per grid cell? (My objects are about half of one 13x13 grid cell. So my images might have ~20 different objects in one image)
- If my objects are really small and the images have a high resolution, how big should my network be? 
Examples: Image sizes can be something between 2100x500 up to  3300x3800.
Objects can be something between 50x70 up to 300x300 pixels.

I'd appreciate every answer or hint.

**Comment by ameeiyn** [comment]
Please check my replies on this thread [ https://github.com/pjreddie/darknet/issues/568# ], Almost all points are covered. If you still have any issue do ping me.

**Comment by Arktius** [comment]
@ameeiyn  Thanks for your reply first. This link provides a lot of use information.
I'll try to summarize my newly gained insights.

- Units for anchor boxes are based on the final feature map (13x13) for yolov2. 13x13 are also the dimensions of the grid cells. Images will be split into 13x13 squares, and each square can predict one object in the end. The final prediction for one cell is determined by the highest IOU (Intersection Over Union). The highest IOU depends obviously on the anchor boxes. In Yolov3 tiny, we have 2 Yolo-layers and therefore 2x3=6 different anchor boxes available, in the usual Yolov3 we have 3 Yolo-layers(3x3=9). So, for Yolov2 we use anchor boxes relative to the grid cells and in Yolov3 we use actual pixel values. 
- This means that using the gen_anchors.py script has to deliver values between 0-13 for Yolov2, where something like width = 12.4 and height 11.8 means that a objects has almost the same size as the entire image. For Yolov3 we use actual pixel values. Use the AlexeyABs repo. It'll output something like this:

num_of_clusters = 6, width = 416, height = 416 
 read labels from 40 images 
 loaded 	 image: 40 	 box: 670
 all loaded. 

 calculating k-means++ ...

 iterations = 37 


 avg IoU = 75.24 % 

Saving anchors to the file: anchors.txt 
anchors =  14,  9,  14, 17,  11, 32,  20, 30,  15, 62,  45, 78

Since we're now working with pixel values, we need integer numbers and we can use the raw output.

- The number of grid cells depends on the network size width and height. Both have to be a multiple of 32. Example: 416 / 32 = 13. If we now use 608, then we'll get 608 / 32 = 19. If your network isn't square, you'll get rectangular grid cells. Example width = 416 and height 608 -> 13x19 grid cells.

**Comment by klopezlinar** [comment]
Hi all,

We're struggling to get our **Yolov3** working for a 2 class detection problem (the size of the objects of both classes are varying and similar, generally small, and the size itself does not help differentiating the object type). We think that the training is not working  due to some problem with the anchor boxes, since we can clearly see that depending on the assigned anchor values the yolo_output_0, yolo_output_1 or yolo_output_2 fail to return a loss value different to 0 (for xy, hw and class components). However, even if there are multiple threads about anchor boxes we cannot find a clear explanation about how they are assigned **specifically for YOLOv3**.

So far, what we're doing to know the size of the boxes is:
1- We run a clustering method on the normalized ground truth bounding boxes (according to the original size of the image) and get the centroids of the clusters. In our case, we have 2 clusters and the centroids are something about (0.087, 0.052) and (0.178, 0.099).
2- Then we rescale the values according to the rescaling we are going to apply to the images during training. We are working with **rectangular** images of (256, 416), so we get bounding boxes of (22,22) and (46,42). Note that we have rounded the values as we have read that yoloV3 expects actual pixel values.
3- Since we compute anchors at 3 different scales (3 skip connections), the previous anchor values will correspond to the large scale (52). The anchors for the other two scales (13 and 26) are calculated by dividing the first ancho /2 and /4.

We are not even sure if we are correct up to this point. If we look at the code in the original models.py what we see is the following:

yolo_anchors = np.array([(10, 13), (16, 30), (33, 23), (30, 61), (62, 45), (59, 119), (116, 90), (156, 198), (373, 326)], np.float32) / 416 
yolo_anchor_masks = np.array([[6, 7, 8], [3, 4, 5], [0, 1, 2]])

So, there are 9 anchors, which are ordered from smaller to larger and the, the anchor_masks determine if the resolution at which they are used, is this correct? In fact, our first question is, are they 9 anchors or 3 anchors at 3 different scales? If so, how are they calculated? we know about the gen_anchors script in yolo_v2 and a similar script in yolov3, however we don't know if they calculate 9 clusters and then order them according to the size or if they follow a procedure similar to ours. 

Additionally, we don’t fully understand why these boxes are divided by 416 (image size). This would mean having anchors that are not integers (pixels values), which was stated was necessary for yolov3. 

We would be really grateful if someone could provide us with some insight into these questions and help us better understanding how yoloV3 performs.

Thanks and regards
Karen

**Comment by Arktius** [comment]
> So far, what we're doing to know the size of the boxes is:
> 1- We run a clustering method on the normalized ground truth bounding boxes (according to the original size of the image) and get the centroids of the clusters. In our case, we have 2 clusters and the centroids are something about (0.087, 0.052) and (0.178, 0.099).

Jep.

> 2- Then we rescale the values according to the rescaling we are going to apply to the images during training. We are working with **rectangular** images of (256, 416), so we get bounding boxes of (22,22) and (46,42). Note that we have rounded the values as we have read that yoloV3 expects actual pixel values.

Sounds good so far! Do the images have similar resolutions? Would be nice. 

> 3- Since we compute anchors at 3 different scales (3 skip connections), the previous anchor values will correspond to the large scale (52). The anchors for the other two scales (13 and 26) are calculated by dividing the first ancho /2 and /4.

> So, there are 9 anchors, which are ordered from smaller to larger and the, the anchor_masks determine if the resolution at which they are used, is this correct?

The largest anchor boxes come first in the config file. Your image shrinks after applying multiple convolutions.

> In fact, our first question is, are they 9 anchors or 3 anchors at 3 different scales?

There's an object '[yolo]' in the config file. It actually appears several times. Same holds for the parameter 'scale'.  It's written that YOLOv3 has 3 scales. [Paper](https://pjreddie.com/media/files/papers/YOLOv3.pdf)


> If so, how are they calculated? we know about the gen_anchors script in yolo_v2 and a similar script in yolov3, however we don't know if they calculate 9 clusters and then order them according to the size or if they follow a procedure similar to ours.

They are already sorted in ascending order.
 
> Additionally, we don’t fully understand why these boxes are divided by 416 (image size). This would mean having anchors that are not integers (pixels values), which was stated was necessary for yolov3.

The anchor boxes are integers, the actual labels are floating numbers. Don't mix up these two things.

> yolo_anchors = np.array([(10, 13), (16, 30), (33, 23), (30, 61), (62, 45), (59, 119), (116, 90), (156, 198), (373, 326)], np.float32) / 416

You don't need to divide by 416. That's probably your mistake.
 
> We would be really grateful if someone could provide us with some insight into these questions and help us better understanding how yoloV3 performs.

What are you going to detect?



Additional recommendations:

- Start with a small amount of images (10-20-100,...) in one scale.
- Check if the loss goes down.
- Increase the image size that is fed into YOLO. (Ideally use the same resolutions for your network and all your images)

**Comment by klopezlinar** [comment]
Hi, thanks for your reply. 
> 
> > So far, what we're doing to know the size of the boxes is:
> > 1- We run a clustering method on the normalized ground truth bounding boxes (according to the original size of the image) and get the centroids of the clusters. In our case, we have 2 clusters and the centroids are something about (0.087, 0.052) and (0.178, 0.099).
> 
> Jep.
> 
> > 2- Then we rescale the values according to the rescaling we are going to apply to the images during training. We are working with **rectangular** images of (256, 416), so we get bounding boxes of (22,22) and (46,42). Note that we have rounded the values as we have read that yoloV3 expects actual pixel values.
> 
> Sounds good so far! Do the images have similar resolutions? Would be nice.

The original resolution of the images is not the same
> 
> > 3- Since we compute anchors at 3 different scales (3 skip connections), the previous anchor values will correspond to the large scale (52). The anchors for the other two scales (13 and 26) are calculated by dividing the first ancho /2 and /4.
> 
> > So, there are 9 anchors, which are ordered from smaller to larger and the, the anchor_masks determine if the resolution at which they are used, is this correct?
> 
> The largest anchor boxes come first in the config file. Your image shrinks after applying multiple convolutions.
> 
According to [this](https://github.com/pjreddie/darknet/blob/master/cfg/yolov3.cfg) the largest anchor boxes come at the end (ordered in ascending order), or are we missing something?

anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326

> > In fact, our first question is, are they 9 anchors or 3 anchors at 3 different scales?
> 
> There's an object '[yolo]' in the config file. It actually appears several times. Same holds for the parameter 'scale'. It's written that YOLOv3 has 3 scales. [Paper](https://pjreddie.com/media/files/papers/YOLOv3.pdf)
> 
Could you explain this further? we can't get your point 

> > If so, how are they calculated? we know about the gen_anchors script in yolo_v2 and a similar script in yolov3, however we don't know if they calculate 9 clusters and then order them according to the size or if they follow a procedure similar to ours.
> 
> They are already sorted in ascending order.
> 
> > Additionally, we don’t fully understand why these boxes are divided by 416 (image size). This would mean having anchors that are not integers (pixels values), which was stated was necessary for yolov3.
> 
> The anchor boxes are integers, the actual labels are floating numbers. Don't mix up these two things.
> 
We don't fully understand what are you referring to. 

> > yolo_anchors = np.array([(10, 13), (16, 30), (33, 23), (30, 61), (62, 45), (59, 119), (116, 90), (156, 198), (373, 326)], np.float32) / 416
> 
> You don't need to divide by 416. That's probably your mistake.
> 
Yes, we should remove that part because we are not sure about it. We use the tf implementation in [here](https://github.com/zzh8829/yolov3-tf2/blob/master/yolov3_tf2/models.py) and they do:

yolo_anchors = np.array([(10, 13), (16, 30), (33, 23), (30, 61), (62, 45),
                         (59, 119), (116, 90), (156, 198), (373, 326)],
                        np.float32) / 416
yolo_anchor_masks = np.array([[6, 7, 8], [3, 4, 5], [0, 1, 2]])



> > We would be really grateful if someone could provide us with some insight into these questions and help us better understanding how yoloV3 performs.
> 
> What are you going to detect?

We are detecting masses.

> 
> Additional recommendations:
> 
>     * Start with a small amount of images (10-20-100,...) in one scale.
> 
>     * Check if the loss goes down.
> 
>     * Increase the image size that is fed into YOLO. (Ideally use the same resolutions for your network and all your images)

Thanks for the suggestions

**Comment by Arktius** [comment]
> The original resolution of the images is not the same

This is not bad as it varies so much or you can cover most of the cases with different scales.
 
 
> According to [this](https://github.com/pjreddie/darknet/blob/master/cfg/yolov3.cfg) the largest anchor boxes come at the end (ordered in ascending order), or are we missing something?
> 
> anchors = 10,13, 16,30, 33,23, 30,61, 62,45, 59,119, 116,90, 156,198, 373,326

This is how I have used it:

```
[yolo]
mask = 3,4,5
anchors = 103, 41, 108, 48, 128, 53,  86,108, 143,107, 183,167
....
[yolo]
mask = 0,1,2
anchors = 103, 41, 108, 48, 128, 53,  86,108, 143,107, 183,167
```
 
> Could you explain this further? we can't get your point

Check this out. [Config](https://github.com/pjreddie/darknet/blob/master/cfg/yolov3.cfg)
 
[yolo] appears 3 times. Yolo uses 3 different scales. 

The [tiny YOLO](https://github.com/pjreddie/darknet/blob/master/cfg/yolov3-tiny.cfg) only supports 2 scales because [yolo] appears 2 times.


> Yes, we should remove that part because we are not sure about it. We use the tf implementation in [here](https://github.com/zzh8829/yolov3-tf2/blob/master/yolov3_tf2/models.py) and they do:
> 
> yolo_anchors = np.array([(10, 13), (16, 30), (33, 23), (30, 61), (62, 45),
> (59, 119), (116, 90), (156, 198), (373, 326)],
> np.float32) / 416
> yolo_anchor_masks = np.array([[6, 7, 8], [3, 4, 5], [0, 1, 2]])

They also do this:
    box_wh = tf.exp(box_wh) * anchors in line 168
 

> We are detecting masses.

In order to...?
