### ISSUE TITLE
Multi GPUS bug code inquiry

### ISSUE THREAD

**Issue by leehangyu** [pjreddie/darknet#2053]
Hi,

I am working on customizing ML framework based on darknet.

I found the wired part of code located at darknet/network.c

line 909 ~ 910

cuda_pull_array(l.biases_gpu, l.bias_updates, l.n);
cuda_pull_array(l.weights_gpu, l.weight_updates, l.nweights);

shouldn't "l.bias_updates" be l.bias ????
shouldn't "l.weight_updates" be l.weights ???

These code pull weights and bias from other layers and put into base.

I have no idea why it pulls data from bias and weights then puts into bias_update and weight_updates.

Thanks for your help in advance.

**Comment by AlexeyAB** [comment]
The code works correctly.
Joseph used _updates arrays just as temporary buffers in this case.

I don't know why did he do these chanes, since both are equal: https://github.com/pjreddie/darknet/commit/fc069593f2ccc5d9026d0a65cd650dbac9ea5b3a#diff-3d9e5ebb59e383c1abd50d8539e92057R152-R320



1. There was used previously (pseudo code):
```
base = net[0]
for(i = 1; i < gpus; ++i) merge(net[i], base);
```

2. Currently (pseudo code):
```
base = 0;
for(i = 0; i < gpus; ++i) merge(net[i], base);
```
