### ISSUE TITLE
Getting error: ‘IplImage’ does not name a type when building with latest opencv

### ISSUE THREAD

**Issue by nyierr** [pjreddie/darknet#2177]
I am getting this error when building darknet with opencv enabled:

```
./src/image_opencv.cpp:12:1: error: ‘IplImage’ does not name a type
 IplImage *image_to_ipl(image im)
 ^~~~~~~~
compilation terminated due to -Wfatal-errors.
Makefile:86: recipe for target 'obj/image_opencv.o' failed
make: *** [obj/image_opencv.o] Error 1
```

Any idea how to fix it?

**Comment by nyierr** [comment]
A change by [tiagoshibata|https://github.com/pjreddie/darknet/issues/1347#issuecomment-469886591] resolved this problem and I have built darknet successfully.

However, when ran the following to confirm all is good, I got an error:
```
$ ./darknet imtest data/eagle.jpg
./darknet: error while loading shared libraries: libopencv_highgui.so.4.3: cannot open shared object file: No such file or directory
```

This was resolved by running:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`

**Comment by zleiwang** [comment]
it is not work

**Comment by hcl7** [comment]
./src/image_opencv.cpp:12:1: error: ‘IplImage’ does not name a type
 IplImage *image_to_ipl(image im)
 ^~~~~~~~
compilation terminated due to -Wfatal-errors.
Makefile:86: recipe for target 'obj/image_opencv.o' failed
make: *** [obj/image_opencv.o] Error 1


I have the same problem, why you guys do not correct the project once for all?
