### ISSUE TITLE
Yolov4 darknet makefile error: 182: 

### ISSUE THREAD

**Issue by VishnuRR27** [pjreddie/darknet#2544]
Hey all!
I am very new to compiling and running code on local gpus, i have always used colab so please help me out
i was trying to compile and run yolov4 on my local gpu but everytime i try to run the make command on my linux terminal (ubuntu 18.04) i get this error
nvcc fatal   : Path to libdevice library not specified
Makefile:182: recipe for target 'obj/convolutional_kernels.o' failed
make: *** [obj/convolutional_kernels.o] Error 1
Below is my makefile
__GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0
ZED_CAMERA_v2_8=0

# set GPU=1 and CUDNN=1 to speedup on GPU
# set CUDNN_HALF=1 to further speedup 3 x times (Mixed-precision on Tensor Cores) GPU: Volta, Xavier, Turing and higher
# set AVX=1 and OPENMP=1 to speedup on CPU (if error occurs then set AVX=0)
# set ZED_CAMERA=1 to enable ZED SDK 3.0 and above
# set ZED_CAMERA_v2_8=1 to enable ZED SDK 2.X

USE_CPP=0
DEBUG=0

ARCH= -gencode arch=compute_70,code=[sm_70,compute_70]

OS := $(shell uname)

# GeForce RTX 3070, 3080, 3090
# ARCH= -gencode arch=compute_86,code=[sm_86,compute_86]

# Kepler GeForce GTX 770, GTX 760, GT 740
# ARCH= -gencode arch=compute_30,code=sm_30

# Tesla A100 (GA100), DGX-A100, RTX 3080
# ARCH= -gencode arch=compute_80,code=[sm_80,compute_80]

# Tesla V100
# ARCH= -gencode arch=compute_70,code=[sm_70,compute_70]

# GeForce RTX 2080 Ti, RTX 2080, RTX 2070, Quadro RTX 8000, Quadro RTX 6000, Quadro RTX 5000, Tesla T4, XNOR Tensor Cores
# ARCH= -gencode arch=compute_75,code=[sm_75,compute_75]

# Jetson XAVIER
# ARCH= -gencode arch=compute_72,code=[sm_72,compute_72]

# GTX 1080, GTX 1070, GTX 1060, GTX 1050, GTX 1030, Titan Xp, Tesla P40, Tesla P4
# ARCH= -gencode arch=compute_61,code=sm_61 -gencode arch=compute_61,code=compute_61

# GP100/Tesla P100 - DGX-1
# ARCH= -gencode arch=compute_60,code=sm_60

# For Jetson TX1, Tegra X1, DRIVE CX, DRIVE PX - uncomment:
# ARCH= -gencode arch=compute_53,code=[sm_53,compute_53]

# For Jetson Tx2 or Drive-PX2 uncomment:
# ARCH= -gencode arch=compute_62,code=[sm_62,compute_62]

# For Tesla GA10x cards, RTX 3090, RTX 3080, RTX 3070, RTX A6000, RTX A40 uncomment:
# ARCH= -gencode arch=compute_86,code=[sm_86,compute_86]

VPATH=./src/
EXEC=darknet
OBJDIR=./obj/

ifeq ($(LIBSO), 1)
LIBNAMESO=libdarknet.so
APPNAMESO=uselib
endif

ifeq ($(USE_CPP), 1)
CC=g++
else
CC=gcc
endif

CPP=g++ -std=c++11
NVCC=nvcc
OPTS=-Ofast
LDFLAGS= -lm -pthread
COMMON= -Iinclude/ -I3rdparty/stb/include
CFLAGS=-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC

ifeq ($(DEBUG), 1)
#OPTS= -O0 -g
#OPTS= -Og -g
COMMON+= -DDEBUG
CFLAGS+= -DDEBUG
else
ifeq ($(AVX), 1)
CFLAGS+= -ffp-contract=fast -mavx -mavx2 -msse3 -msse4.1 -msse4.2 -msse4a
endif
endif

CFLAGS+=$(OPTS)

ifneq (,$(findstring MSYS_NT,$(OS)))
LDFLAGS+=-lws2_32
endif

ifeq ($(OPENCV), 1)
COMMON+= -DOPENCV
CFLAGS+= -DOPENCV
LDFLAGS+= `pkg-config --libs opencv4 2> /dev/null || pkg-config --libs opencv`
COMMON+= `pkg-config --cflags opencv4 2> /dev/null || pkg-config --cflags opencv`
endif

ifeq ($(OPENMP), 1)
    ifeq ($(OS),Darwin) #MAC
	    CFLAGS+= -Xpreprocessor -fopenmp
	else
		CFLAGS+= -fopenmp
	endif
LDFLAGS+= -lgomp
endif

ifeq ($(GPU), 1)
COMMON+= -DGPU -I/usr/local/cuda/include/
CFLAGS+= -DGPU
ifeq ($(OS),Darwin) #MAC
LDFLAGS+= -L/usr/local/cuda/lib -lcuda -lcudart -lcublas -lcurand
else
LDFLAGS+= -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcurand
endif
endif

ifeq ($(CUDNN), 1)
COMMON+= -DCUDNN
ifeq ($(OS),Darwin) #MAC
CFLAGS+= -DCUDNN -I/usr/local/cuda/include
LDFLAGS+= -L/usr/local/cuda/lib -lcudnn
else
CFLAGS+= -DCUDNN -I/usr/local/cudnn/include
LDFLAGS+= -L/usr/local/cudnn/lib64 -lcudnn
endif
endif

ifeq ($(CUDNN_HALF), 1)
COMMON+= -DCUDNN_HALF
CFLAGS+= -DCUDNN_HALF
ARCH+= -gencode arch=compute_70,code=[sm_70,compute_70]
endif

ifeq ($(ZED_CAMERA), 1)
CFLAGS+= -DZED_STEREO -I/usr/local/zed/include
ifeq ($(ZED_CAMERA_v2_8), 1)
LDFLAGS+= -L/usr/local/zed/lib -lsl_core -lsl_input -lsl_zed
#-lstdc++ -D_GLIBCXX_USE_CXX11_ABI=0
else
LDFLAGS+= -L/usr/local/zed/lib -lsl_zed
#-lstdc++ -D_GLIBCXX_USE_CXX11_ABI=0
endif
endif

OBJ=image_opencv.o http_stream.o gemm.o utils.o dark_cuda.o convolutional_layer.o list.o image.o activations.o im2col.o col2im.o blas.o crop_layer.o dropout_layer.o maxpool_layer.o softmax_layer.o data.o matrix.o network.o connected_layer.o cost_layer.o parser.o option_list.o darknet.o detection_layer.o captcha.o route_layer.o writing.o box.o nightmare.o normalization_layer.o avgpool_layer.o coco.o dice.o yolo.o detector.o layer.o compare.o classifier.o local_layer.o swag.o shortcut_layer.o representation_layer.o activation_layer.o rnn_layer.o gru_layer.o rnn.o rnn_vid.o crnn_layer.o demo.o tag.o cifar.o go.o batchnorm_layer.o art.o region_layer.o reorg_layer.o reorg_old_layer.o super.o voxel.o tree.o yolo_layer.o gaussian_yolo_layer.o upsample_layer.o lstm_layer.o conv_lstm_layer.o scale_channels_layer.o sam_layer.o
ifeq ($(GPU), 1)
LDFLAGS+= -lstdc++
OBJ+=convolutional_kernels.o activation_kernels.o im2col_kernels.o col2im_kernels.o blas_kernels.o crop_layer_kernels.o dropout_layer_kernels.o maxpool_layer_kernels.o network_kernels.o avgpool_layer_kernels.o
endif

OBJS = $(addprefix $(OBJDIR), $(OBJ))
DEPS = $(wildcard src/*.h) Makefile include/darknet.h

all: $(OBJDIR) backup results setchmod $(EXEC) $(LIBNAMESO) $(APPNAMESO)

ifeq ($(LIBSO), 1)
CFLAGS+= -fPIC

$(LIBNAMESO): $(OBJDIR) $(OBJS) include/yolo_v2_class.hpp src/yolo_v2_class.cpp
	$(CPP) -shared -std=c++11 -fvisibility=hidden -DLIB_EXPORTS $(COMMON) $(CFLAGS) $(OBJS) src/yolo_v2_class.cpp -o $@ $(LDFLAGS)

$(APPNAMESO): $(LIBNAMESO) include/yolo_v2_class.hpp src/yolo_console_dll.cpp
	$(CPP) -std=c++11 $(COMMON) $(CFLAGS) -o $@ src/yolo_console_dll.cpp $(LDFLAGS) -L ./ -l:$(LIBNAMESO)
endif

$(EXEC): $(OBJS)
	$(CPP) -std=c++11 $(COMMON) $(CFLAGS) $^ -o $@ $(LDFLAGS)

$(OBJDIR)%.o: %.c $(DEPS)
	$(CC) $(COMMON) $(CFLAGS) -c $< -o $@

$(OBJDIR)%.o: %.cpp $(DEPS)
	$(CPP) -std=c++11 $(COMMON) $(CFLAGS) -c $< -o $@

$(OBJDIR)%.o: %.cu $(DEPS)
	$(NVCC) $(ARCH) $(COMMON) --compiler-options "$(CFLAGS)" -c $< -o $@

$(OBJDIR):
	mkdir -p $(OBJDIR)
backup:
	mkdir -p backup
results:
	mkdir -p results
setchmod:
	chmod +x *.sh

.PHONY: clean

clean:
	rm -rf $(OBJS) $(EXEC) $(LIBNAMESO) $(APPNAMESO)__

**Comment by Rusali28** [comment]
Hey, I am getting the same error. Were you able to solve it?

**Comment by VishnuRR27** [comment]
@Rusali28 I did not dive very deep and spend a lot of time fixing it, it ran perfectly on colab. But based on the information i could collect, it maybe an openCV version mismatch that maybe causing the error

**Comment by Rusali28** [comment]
@VishnuRR27 Did you run it on colab free, or colab pro? In case of colab free, I am facing the error while trying to change the gpu architecture specification to the one assigned on colab free. Did you encounter a similar case while resolving your error?

**Comment by VishnuRR27** [comment]
@Rusali28 No I did not face any errors on both colab pro and the free version, you don't have to make any changes to the make file except the ones mentioned in their tutorial notebook if you are running on colab. If you are still facing an error could you please paste the error message so that there is more clarity about the error

**Comment by Rusali28** [comment]
@VishnuRR27 I tried running the colab free notebook authored by Roboflow, which helps me to train a YOLOv4 model on my custom generated dataset. (The link to the notebook for your kind reference - [https://colab.research.google.com/drive/1mzL6WyY9BRx4xX476eQdhKDnd_eixBlG?ref=roboflow-blog#scrollTo=u-bguKWgtxSx](url) ).
I am simply trying to run the cells in this notebook, and while installing the Darknet environment through the makefile (8th code cell in the notebook), it suggests that I might have to change the gpu specification as assigned to me by colab free. 
Although I tried multiple ways of doing that, everything still results in the same error as I was getting with or without changing the gpu specification. The error is as follows- 

`/content/darknet
chmod +x *.sh
g++ -std=c++11 -std=c++11 -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4 2> /dev/null || pkg-config --cflags opencv` -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/image_opencv.cpp -o obj/image_opencv.o
./src/image_opencv.cpp: In function ‘void draw_detections_cv_v3(void**, detection*, int, float, char**, image**, int, int)’:
./src/image_opencv.cpp:910:23: warning: variable ‘rgb’ set but not used [-Wunused-but-set-variable]
  910 |                 float rgb[3];
      |                       ^~~
./src/image_opencv.cpp: In function ‘void cv_draw_object(image, float*, int, int, int*, float*, int*, int, char**)’:
./src/image_opencv.cpp:1391:14: warning: unused variable ‘buff’ [-Wunused-variable]
 1391 |         char buff[100];
      |              ^~~~
./src/image_opencv.cpp:1367:9: warning: unused variable ‘it_tb_res’ [-Wunused-variable]
 1367 |     int it_tb_res = cv::createTrackbar(it_trackbar_name, window_name, &it_trackbar_value, 1000);
      |         ^~~~~~~~~
./src/image_opencv.cpp:1371:9: warning: unused variable ‘lr_tb_res’ [-Wunused-variable]
 1371 |     int lr_tb_res = cv::createTrackbar(lr_trackbar_name, window_name, &lr_trackbar_value, 20);
      |         ^~~~~~~~~
./src/image_opencv.cpp:1375:9: warning: unused variable ‘cl_tb_res’ [-Wunused-variable]
 1375 |     int cl_tb_res = cv::createTrackbar(cl_trackbar_name, window_name, &cl_trackbar_value, classes-1);
      |         ^~~~~~~~~
./src/image_opencv.cpp:1378:9: warning: unused variable ‘bo_tb_res’ [-Wunused-variable]
 1378 |     int bo_tb_res = cv::createTrackbar(bo_trackbar_name, window_name, boxonly, 1);
      |         ^~~~~~~~~
g++ -std=c++11 -std=c++11 -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4 2> /dev/null || pkg-config --cflags opencv` -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/http_stream.cpp -o obj/http_stream.o
In file included from ./src/http_stream.cpp:580:
./src/httplib.h:129: warning: "INVALID_SOCKET" redefined
  129 | #define INVALID_SOCKET (-1)
      | 
./src/http_stream.cpp:73: note: this is the location of the previous definition
   73 | #define INVALID_SOCKET -1
      | 
./src/http_stream.cpp: In member function ‘bool JSON_sender::write(const char*)’:
./src/http_stream.cpp:249:21: warning: unused variable ‘n’ [-Wunused-variable]
  249 |                 int n = _write(client, outputbuf, outlen);
      |                     ^
./src/http_stream.cpp: In member function ‘bool MJPG_sender::write(const cv::Mat&)’:
./src/http_stream.cpp:507:95: warning: format ‘%zu’ expects argument of type ‘size_t’, but argument 3 has type ‘int’ [-Wformat=]
  507 |                 sprintf(head, "--mjpegstream\r\nContent-Type: image/jpeg\r\nContent-Length: %zu\r\n\r\n", outlen);
      |                                                                                             ~~^           ~~~~~~
      |                                                                                               |           |
      |                                                                                               |           int
      |                                                                                               long unsigned int
      |                                                                                             %u
gcc -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4 2> /dev/null || pkg-config --cflags opencv` -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/gemm.c -o obj/gemm.o
./src/gemm.c: In function ‘convolution_2d’:
./src/gemm.c:2039:15: warning: unused variable ‘out_w’ [-Wunused-variable]
 2039 |     const int out_w = (w + 2 * pad - ksize) / stride + 1;    // output_width=input_width for stride=1 and pad=1
      |               ^~~~~
./src/gemm.c:2038:15: warning: unused variable ‘out_h’ [-Wunused-variable]
 2038 |     const int out_h = (h + 2 * pad - ksize) / stride + 1;    // output_height=input_height for stride=1 and pad=1
      |               ^~~~~
gcc -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4 2> /dev/null || pkg-config --cflags opencv` -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/utils.c -o obj/utils.o
In file included from /usr/include/string.h:495,
                 from include/darknet.h:14,
                 from ./src/utils.h:3,
                 from ./src/utils.c:4:
In function ‘strncpy’,
    inlined from ‘copy_string’ at ./src/utils.c:509:5:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./src/utils.c: In function ‘copy_string’:
./src/utils.c:509:22: note: length computed here
  509 |     strncpy(copy, s, strlen(s)+1);
      |                      ^~~~~~~~~
gcc -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4 2> /dev/null || pkg-config --cflags opencv` -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/dark_cuda.c -o obj/dark_cuda.o
./src/dark_cuda.c: In function ‘cudnn_check_error_extended’:
./src/dark_cuda.c:224:20: warning: comparison between ‘cudaError_t’ {aka ‘enum cudaError’} and ‘enum <anonymous>’ [-Wenum-compare]
  224 |         if (status != CUDNN_STATUS_SUCCESS)
      |                    ^~
./src/dark_cuda.c: In function ‘pre_allocate_pinned_memory’:
./src/dark_cuda.c:276:40: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  276 |         printf("pre_allocate: size = %Iu MB, num_of_blocks = %Iu, block_size = %Iu MB \n",
      |                                      ~~^
      |                                        |
      |                                        unsigned int
      |                                      %Ilu
  277 |             size / (1024*1024), num_of_blocks, pinned_block_size / (1024 * 1024));
      |             ~~~~~~~~~~~~~~~~~~          
      |                  |
      |                  long unsigned int
./src/dark_cuda.c:276:64: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t’ {aka ‘const long unsigned int’} [-Wformat=]
  276 |         printf("pre_allocate: size = %Iu MB, num_of_blocks = %Iu, block_size = %Iu MB \n",
      |                                                              ~~^
      |                                                                |
      |                                                                unsigned int
      |                                                              %Ilu
  277 |             size / (1024*1024), num_of_blocks, pinned_block_size / (1024 * 1024));
      |                                 ~~~~~~~~~~~~~                   
      |                                 |
      |                                 size_t {aka const long unsigned int}
./src/dark_cuda.c:276:82: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘long unsigned int’ [-Wformat=]
  276 |         printf("pre_allocate: size = %Iu MB, num_of_blocks = %Iu, block_size = %Iu MB \n",
      |                                                                                ~~^
      |                                                                                  |
      |                                                                                  unsigned int
      |                                                                                %Ilu
  277 |             size / (1024*1024), num_of_blocks, pinned_block_size / (1024 * 1024));
      |                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
      |                                                                  |
      |                                                                  long unsigned int
./src/dark_cuda.c:286:37: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  286 |                 printf(" Allocated %d pinned block \n", pinned_block_size);
      |                                    ~^                   ~~~~~~~~~~~~~~~~~
      |                                     |                   |
      |                                     int                 long unsigned int
      |                                    %ld
./src/dark_cuda.c: In function ‘cuda_make_array_pinned_preallocated’:
./src/dark_cuda.c:307:43: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
  307 |             printf("\n Pinned block_id = %d, filled = %f %% \n", pinned_block_id, filled);
      |                                          ~^                      ~~~~~~~~~~~~~~~
      |                                           |                      |
      |                                           int                    size_t {aka long unsigned int}
      |                                          %ld
./src/dark_cuda.c:322:64: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  322 |             printf("Try to allocate new pinned memory, size = %d MB \n", size / (1024 * 1024));
      |                                                               ~^         ~~~~~~~~~~~~~~~~~~~~
      |                                                                |              |
      |                                                                int            long unsigned int
      |                                                               %ld
./src/dark_cuda.c:328:63: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  328 |             printf("Try to allocate new pinned BLOCK, size = %d MB \n", size / (1024 * 1024));
      |                                                              ~^         ~~~~~~~~~~~~~~~~~~~~
      |                                                               |              |
      |                                                               int            long unsigned int
      |                                                              %ld
gcc -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4 2> /dev/null || pkg-config --cflags opencv` -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/convolutional_layer.c -o obj/convolutional_layer.o
./src/convolutional_layer.c: In function ‘cudnn_convolutional_setup’:
./src/convolutional_layer.c:286:24: error: ‘CUDNN_CONVOLUTION_FWD_PREFER_FASTEST’ undeclared (first use in this function); did you mean ‘CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3’?
  286 |     int forward_algo = CUDNN_CONVOLUTION_FWD_PREFER_FASTEST;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:144: obj/convolutional_layer.o] Error 1` 


Please let me know if you can help me figure this out, thanks a lot for your time!

**Comment by VishnuRR27** [comment]
@Rusali28 I think the link you sent directs me to your drive so I am not able to access the notebook. I suggest you try this tutorial notebook (in case you haven't tried it yet), the instructions are quite self explanatory. This is the notebook I use even today and I do not face any errors. I am suggesting this because you said you are just running the cells.
https://colab.research.google.com/drive/1_GdoqCJWXsChrOiY8sZMr_zbr_fH-0Fg#scrollTo=A9mYUoKOWWlR
You can also refer to this repository or even tag me for any clarifications
https://github.com/AlexeyAB/darknet#yolo-v4-v3-and-v2-for-windows-and-linux
Here is the link to the colab tutorial file.

**Comment by VishnuRR27** [comment]
> @Rusali28 I think the link you sent directs me to your drive so I am not able to access the notebook. I suggest you try this tutorial notebook (in case you haven't tried it yet), the instructions are quite self explanatory. This is the notebook I use even today and I do not face any errors. I am suggesting this because you said you are just running the cells.
> https://colab.research.google.com/drive/1_GdoqCJWXsChrOiY8sZMr_zbr_fH-0Fg#scrollTo=A9mYUoKOWWlR
> You can also refer to this repository or even tag me for any clarifications
> https://github.com/AlexeyAB/darknet#yolo-v4-v3-and-v2-for-windows-and-linux
> Here is the link to the colab tutorial file. 
> 

@Rusali28 I updated the colab notebook link i mentioned here, it was the wrong link 
Sorry for the inconvenience caused

**Comment by Rusali28** [comment]
@VishnuRR27 Thanks for updating the correct link, I did check it out and go through it. However, the problem I am facing is that my custom dataset is generated on roboflow so it is more convenient to use the file that automatically reads the data into required directories with proper divisions. I went through the part of your notebook that shows how to custom train, but those instructions dont match with my roboflow dataset (for eg. I dont have a .cfg file in my dataset).
I am sorry you couldn't access my linked notebook earlier, hence I am uploading it as a file here, as well as a link again. Please can you have a look over it and let me know? 
[https://colab.research.google.com/drive/1pelTbgaIpBKuCkj6MplyyCsszH3KN5lw?usp=sharing](url)
[YOLOv4_Darknet_Roboflow.pdf](https://github.com/pjreddie/darknet/files/10990090/YOLOv4_Darknet_Roboflow.pdf)

Thank you for you time and support!

**Comment by VishnuRR27** [comment]
@Rusali28 The instructions about the .cfg file and other files are given in the repository I mentioned in the previous comment. In fact it is exactly the custom cfg file you are creating in your notebook with some edits mentioned in the repo, you can use your custom cfg file for training in the notebook I mentioned.
However I went through your notebook and made some small changes (imported the makefile from the original repo) and the !make command did not give any errors, hopefully this works for you. (ignore any warnings)
https://colab.research.google.com/drive/1Jli8QbmoXzo8t67kw901f_icJ76RrrGO
The link to the notebook where changes were made.
In case you are looking forward to using the notebook I linked earlier, I have attached the standard yolov4.cfg file below as a txt file, you can just change the extension as required.
[yolov4-obj.txt](https://github.com/pjreddie/darknet/files/10991916/yolov4-obj.txt)

**Comment by Rusali28** [comment]
@VishnuRR27 Yes, I am able to run it now. Thank you very much for your help!

**Comment by VishnuRR27** [comment]
@Rusali28 Glad to help, will be closing this issue with this comment
