### ISSUE TITLE
Website SSL Certificate Expired

### ISSUE THREAD

**Issue by adamsong** [pjreddie/darknet#313]
This may be the incorrect place to put this but the SSL certificate for https://pjreddie.com/ has expired and due to the implementation of HSTS the website is unavailable.

**Comment by pjreddie** [comment]
ENABLE ENCRYPTION THEY TOLD ME

IT'S SO EASY ANYONE CAN DO IT THEY SAID

but yeah, i think it should be back now, thanks. this happens pretty regularly every year, i think the problem is i'm not restarting the right service after updating the cert but i don't get many opportunities to test this theory.

**Comment by adamsong** [comment]
It works on my end now as well
