### ISSUE TITLE
How does Darknet do regression tasks?

### ISSUE THREAD

**Issue by CBIR-LL** [pjreddie/darknet#322]
How does Darknet do regression tasks? Can someone give me some advice?

**Comment by drapado** [comment]
Hi, I'm trying to do a regression task on darknet as well (kind of scoring images from 1 to 10 or multiple scores per image). I haven't found much information in how to do it in darknet. Did you managed to do it? If so, can you give some advice?

Thanks a lot!

**Comment by drapado** [comment]
@CBIR-LL

**Comment by shebna12** [comment]
@Li-Lai  @drapado Were you able to figure it out? 
So far, I think I can change darknet's activation into linear to frame the regression-like task. I'm planning on changing the filters in the last convolutional layer but I don't have a definite number of classes for it(since it's regression). Also, I don't know what to put in the data file of my dataset. The `classes` variable and `labels `variable would be empty in the case of regression. I'm having a road block here onwards.   Thanks!

**Comment by drapado** [comment]
Hi @shebna12,
In the end I worked on pytorch since it was much simpler to use and adapt. I used this [repo](https://github.com/ultralytics/yolov3).
