### ISSUE TITLE
Remove some labels from the 9000 labels

### ISSUE THREAD

**Issue by arjunfzk** [pjreddie/darknet#542]
What if i want to remove some objects from the 9000 labels ? 
how do i do it? I tried editing the label txt file but it gives segmentation error.

**Comment by TheMikeyR** [comment]
1. Remove the class from names.txt
2. Update this line in the cfg you are using (I assumed yolo9000.cfg) to the number of classes https://github.com/pjreddie/darknet/blob/80d9bec20f0a44ab07616215c6eadb2d633492fe/cfg/yolo9000.cfg#L201
3. Update in same cfg file (I assumed yolo9000.cfg) the last layer filter size to filters=(classes + 5) * 5, so if classes=2 then should be filters=35. Or if you use classes=1 then write filters=30. https://github.com/pjreddie/darknet/blob/80d9bec20f0a44ab07616215c6eadb2d633492fe/cfg/yolo9000.cfg#L192
4. Not sure if this is necessary but I assume it is, you need to crawl through all label files and delete all lines with the classes you have deleted, should be fine since you can just scan for the class number.
4a. You probably also need to update the number of the rest of the classes so they match names.txt file (line 0 = class 0, line 7 = class 7 etc.). Should probably do this step at the same time, so you can crawl through one file at the time, delete line with the class you don't want and update the classes to whatever new number they fit with in names.txt
