### ISSUE TITLE
Filters for convolution and Reason for very large anchors

### ISSUE THREAD

**Issue by ahsan856jalal** [pjreddie/darknet#562]
@pjreddie  
In yolo v2, filters for the last convolution layer was set as 
filters=125 (classes+1+coords)*num
If:
num=5
classes=20
coords=4

How you set filters=75 for classes=20, num=9 and coords=4 ?
Moreover, anchors in yolov2 were not as big as yolo v3 , is it fine or should we use kmeans on width and height and get best ratios from there ?

**Comment by fabito** [comment]
According to paper:

> ... we predict 3 boxes at each scale so the tensor
> is N ×N ×[3∗(4+ 1+ 80)] for the 4 bounding box offsets,
> 1 objectness prediction, and 80 class predictions. ...

`85*3  = 255` for COCO
`25*3 = 75` for PASCAL VOC

Still trying to figure out the difference in anchors size.

**Comment by AlexeyAB** [comment]
Now anchors depends on size of the network-input rather than size of the network-output (final-feature-map): https://github.com/pjreddie/darknet/issues/555#issuecomment-376190325
So values of the anchors 32 times more.

Now `filters=(classes+1+coords)*anchors_num` where anchors_num is a number of `mask`s for this layer.
If `mask` is absence then `anchors_num = num` for this layer: https://github.com/pjreddie/darknet/blob/e4acba689c89e223636efe7dabe8f55ae019cd8a/src/yolo_layer.c#L31-L37
Each `[yolo]` layer uses only those anchors whose indices are specified in the `mask=`

**Comment by ahsan856jalal** [comment]
so if I am seeing a value 330 in anchors , it is 330/13 in yolov2 right?
